services:
  pdsoft-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING.MAIL.USERNAME=${EMAIL_FROM}
      - SPRING.NAME.PASSWORD=${EMAIL_PASS}
      - API.KEY=${DOCRAPTOR_KEY}
      - API.TEST=${DOCRAPTOR_TEST}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0.39
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Habilita el puerto HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html  # Para validación HTTP
    depends_on:
      - pdsoft-app
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
