user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    # Redirige HTTP a HTTPS
    server {
        listen 80;
        server_name url;
        return 301 https://$host$request_uri;
    }

    # Configuración HTTPS
    server {
        listen 443 ssl;
        server_name url_del_sitio;

        ssl_certificate /etc/nginx/certs/fullchain.crt;
        ssl_certificate_key /etc/nginx/certs/certificado.key;
        ssl_trusted_certificate /etc/nginx/certs/certificado.crt;

        location / {
            proxy_pass http://pdsoft-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cookie_path / "/; HttpOnly; Secure; SameSite=Strict";
        }

        # Para validación HTTP (renovaciones futuras)
        location /.well-known/pki-validation/ {
            root /usr/share/nginx/html;
        }
    }
}
